In [1]:
import pywhatkit


In [2]:
pywhatkit.sendwhatmsg_instantly("+919667282651","Welcome")

In [1]:
import requests

In [2]:
help(requests)

Help on package requests:

NAME
    requests

DESCRIPTION
    Requests HTTP Library
    ~~~~~~~~~~~~~~~~~~~~~

    Requests is an HTTP library, written in Python, for human beings.
    Basic GET usage:

       >>> import requests
       >>> r = requests.get('https://www.python.org')
       >>> r.status_code
       200
       >>> b'Python is a programming language' in r.content
       True

    ... or POST:

       >>> payload = dict(key1='value1', key2='value2')
       >>> r = requests.post('https://httpbin.org/post', data=payload)
       >>> print(r.text)
       {
         ...
         "form": {
           "key1": "value1",
           "key2": "value2"
         },
         ...
       }

    The other HTTP methods are supported - see `requests.api`. Full documentation
    is at <https://requests.readthedocs.io>.

    :copyright: (c) 2017 by Kenneth Reitz.
    :license: Apache 2.0, see LICENSE for more details.

PACKAGE CONTENTS
    __version__
    _internal_utils
    adapters
    api
  

In [3]:
import Skype4Py

ModuleNotFoundError: No module named 'Skype4Py'

In [6]:
if():
    print("linux")
else:
    print("World")

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3183764219.py, line 1)

In [1]:
import cv2

In [2]:
cap=cv2.VideoCapture(0)

In [3]:
photo=cap.read()

In [5]:
cv2.imwrite("Mushahid.jpeg",photo[1])

True

In [1]:
cv2.imshow("Mushahid Photo",photo[1])
cv2.waitkey(5000)


NameError: name 'cv2' is not defined

In [2]:
import cv2

In [4]:
cap=cv2.VideoCapture(0)

In [13]:
status,photo=cap.read()

In [12]:
cv2.imshow("Mushahid Photo",photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [14]:
cap.release()

In [15]:
cv2.imshow("Mushahid Photo",photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [16]:
import numpy

In [17]:
type(photo)


numpy.ndarray

In [18]:
photo.shape

(480, 640, 3)

In [19]:
help(photo.shape)

Help on tuple object:

class tuple(object)
 |  tuple(iterable=(), /)
 |
 |  Built-in immutable sequence.
 |
 |  If no argument is given, the constructor returns an empty tuple.
 |  If iterable is specified the tuple is initialized from iterable's items.
 |
 |  If the argument is a tuple, the return value is the same object.
 |
 |  Built-in subclasses:
 |      asyncgen_hooks
 |      UnraisableHookArgs
 |
 |  Methods defined here:
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __contains__(self, key, /)
 |      Return bool(key in self).
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getitem__(self, key, /)
 |      Return self[key].
 |
 |  __getnewargs__(self, /)
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __hash__(self, /)
 |      Return hash(self).
 |
 |  __iter__(self, /)
 |      Implement iter(sel

In [20]:
photo


array([[[126, 147, 149],
        [131, 146, 149],
        [137, 145, 146],
        ...,
        [141, 149, 148],
        [146, 152, 152],
        [147, 152, 152]],

       [[126, 147, 148],
        [132, 147, 147],
        [138, 146, 146],
        ...,
        [138, 146, 146],
        [140, 148, 147],
        [143, 151, 150]],

       [[142, 147, 147],
        [141, 149, 148],
        [139, 149, 148],
        ...,
        [124, 142, 143],
        [117, 137, 140],
        [127, 148, 151]],

       ...,

       [[ 37,  47,  49],
        [ 35,  46,  47],
        [ 33,  46,  45],
        ...,
        [ 43,  68,  75],
        [ 48,  68,  75],
        [ 48,  68,  75]],

       [[ 35,  47,  50],
        [ 34,  46,  48],
        [ 33,  45,  46],
        ...,
        [ 40,  69,  74],
        [ 37,  67,  71],
        [ 35,  64,  68]],

       [[ 27,  45,  48],
        [ 26,  44,  46],
        [ 28,  44,  45],
        ...,
        [ 39,  66,  76],
        [ 37,  63,  72],
        [ 39,  65,  74]]

In [21]:
photo[0][0]

array([126, 147, 149], dtype=uint8)

In [24]:
photo[100]=[0,255,0]

In [25]:
cv2.imshow("Mushahid Photo",photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [26]:
photo[100]


array([[  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0],
       ...,
       [  0, 255,   0],
       [  0, 255,   0],
       [  0, 255,   0]], dtype=uint8)

In [27]:
photo.shape


(480, 640, 3)

In [28]:
photo[100:300]


array([[[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[155, 165, 176],
        [153, 165, 173],
        [150, 163, 169],
        ...,
        [142, 137, 143],
        [150, 133, 142],
        [159, 140, 149]],

       [[150, 164, 175],
        [147, 165, 172],
        [143, 164, 167],
        ...,
        [142, 143, 150],
        [147, 143, 153],
        [147, 143, 153]],

       ...,

       [[123, 135, 147],
        [122, 136, 142],
        [125, 140, 139],
        ...,
        [114, 136, 139],
        [118, 144, 146],
        [113, 139, 141]],

       [[120, 137, 147],
        [126, 139, 143],
        [131, 139, 139],
        ...,
        [118, 134, 139],
        [120, 138, 143],
        [121, 139, 144]],

       [[133, 135, 144],
        [134, 137, 141],
        [134, 139, 139],
        ...,
        [126, 137, 142],
        [129, 139, 142],
        [130, 139, 142]]

In [33]:
cv2.imshow("Mushahid Photo",photo[100:300,300:5500])
cv2.waitKey()
cv2.destroyAllWindows()

In [34]:
photo=photo[:,:,

In [35]:
cv2.imshow("Mushahid Photo",photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [38]:
photo+=150

In [39]:
cv2.imshow("Mushahid Photo",photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [2]:
import smtplib

In [3]:
s=smtplib.SMTP('smtp.gmail.com',587)
s.starttls()

(220, b'2.0.0 Ready to start TLS')

In [4]:
s.login("md.mushahidansari@gmail.com","7050929556Gg@")

SMTPAuthenticationError: (534, b'5.7.9 Application-specific password required. For more information, go to\n5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor d2e1a72fcca58-708044ac343sm8777564b3a.160 - gsmtp')